"""journal de moderation

Revision ID: 3aa399cff0e3
Revises: c994352a1754
Create Date: 2026-08-12 09:19:25.083816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa399cff0e3'
down_revision = 'c994352a1754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moderation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moderation_logs_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moderation_logs_created_at'))

    op.drop_table('moderation_logs')
    # ### end Alembic commands ###
