"""module pulaar phase 1 - termes sources domaines propositions

Revision ID: 45686c2c9466
Revises: b483485d15db
Create Date: 2026-09-01 01:59:04.576261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45686c2c9466'
down_revision = 'b483485d15db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pulaar_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('pulaar_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pulaar_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_lemma', sa.String(length=200), nullable=False),
    sa.Column('definition_fr', sa.Text(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('proposed_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['pulaar_domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pulaar_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lemma', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('part_of_speech', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['pulaar_domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['pulaar_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pulaar_terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pulaar_terms_slug'), ['slug'], unique=True)

    op.create_table('pulaar_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['pulaar_terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pulaar_definitions')
    with op.batch_alter_table('pulaar_terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pulaar_terms_slug'))

    op.drop_table('pulaar_terms')
    op.drop_table('pulaar_proposals')
    op.drop_table('pulaar_sources')
    op.drop_table('pulaar_domains')
    # ### end Alembic commands ###
