"""seuil similarite sujets

Revision ID: 750dc499cf93
Revises: 8e9409f750e0
Create Date: 2026-08-11 20:36:55.717436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750dc499cf93'
down_revision = '8e9409f750e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scoring_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_similarity_threshold', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scoring_configs', schema=None) as batch_op:
        batch_op.drop_column('topic_similarity_threshold')

    # ### end Alembic commands ###
