"""mode contenu integral sources gouv

Revision ID: 8baa42d6f2b6
Revises: 3aa399cff0e3
Create Date: 2026-08-14 03:32:17.381025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8baa42d6f2b6'
down_revision = '3aa399cff0e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collected_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_full', sa.Text(), nullable=True))

    with op.batch_alter_table('sources', schema=None) as batch_op:
        # server_default indispensable ici : les sources déjà en base (créées
        # avant cette migration) doivent recevoir une valeur pour ces deux
        # colonnes NOT NULL au moment même de l'ALTER TABLE, avant qu'aucun
        # code Python n'ait la main pour la leur fournir. Sans ça, la
        # migration échoue sur toute base qui contient déjà au moins une
        # source (vérifié : IntegrityError sur NOT NULL constraint failed).
        batch_op.add_column(sa.Column(
            'source_category', sa.String(length=20), nullable=False,
            server_default='media',
        ))
        batch_op.add_column(sa.Column(
            'content_mode', sa.String(length=20), nullable=False,
            server_default='extrait',
        ))
        batch_op.add_column(sa.Column('content_license_justification', sa.Text(), nullable=True))
        batch_op.create_check_constraint('ck_source_integral_requires_justification', "content_mode = 'extrait' OR (source_category != 'media' AND content_license_justification IS NOT NULL AND length(content_license_justification) >= 20)")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_constraint('ck_source_integral_requires_justification', type_='check')
        batch_op.drop_column('content_license_justification')
        batch_op.drop_column('content_mode')
        batch_op.drop_column('source_category')

    with op.batch_alter_table('collected_articles', schema=None) as batch_op:
        batch_op.drop_column('content_full')

    # ### end Alembic commands ###
