"""agregation sources

Revision ID: 8e9409f750e0
Revises: 971c78d38345
Create Date: 2026-08-11 13:36:25.922374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9409f750e0'
down_revision = '971c78d38345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight_importance', sa.Float(), nullable=False),
    sa.Column('weight_freshness', sa.Float(), nullable=False),
    sa.Column('weight_popularity', sa.Float(), nullable=False),
    sa.Column('weight_relevance', sa.Float(), nullable=False),
    sa.Column('weight_trust', sa.Float(), nullable=False),
    sa.Column('threshold_high', sa.Float(), nullable=False),
    sa.Column('threshold_medium', sa.Float(), nullable=False),
    sa.Column('threshold_low', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('representative_title', sa.String(length=300), nullable=False),
    sa.Column('sources_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('site_url', sa.String(length=300), nullable=False),
    sa.Column('feed_url', sa.String(length=400), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('trust_level', sa.Integer(), nullable=False),
    sa.Column('fetch_frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('keywords_include', sa.String(length=500), nullable=True),
    sa.Column('keywords_exclude', sa.String(length=500), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('compliance_checked', sa.Boolean(), nullable=False),
    sa.Column('compliance_notes', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('is_active = FALSE OR compliance_checked = TRUE', name='ck_source_active_requires_compliance'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('collected_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score_total', sa.Float(), nullable=True),
    sa.Column('score_importance', sa.Float(), nullable=True),
    sa.Column('score_freshness', sa.Float(), nullable=True),
    sa.Column('score_popularity', sa.Float(), nullable=True),
    sa.Column('score_relevance', sa.Float(), nullable=True),
    sa.Column('score_trust', sa.Float(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('published_article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['published_article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_url', name='uq_collected_source_url')
    )
    with op.batch_alter_table('collected_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collected_articles_collected_at'), ['collected_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collected_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collected_articles_collected_at'))

    op.drop_table('collected_articles')
    op.drop_table('sources')
    op.drop_table('topics')
    op.drop_table('scoring_configs')
    # ### end Alembic commands ###
