"""integration reseaux sociaux articles

Revision ID: 90893b39bfc8
Revises: 8baa42d6f2b6
Create Date: 2026-08-18 19:24:10.602935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90893b39bfc8'
down_revision = '8baa42d6f2b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('source_platform', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('source_platform')
        batch_op.drop_column('source_url')

    # ### end Alembic commands ###
