"""correspondants whatsapp

Revision ID: 971c78d38345
Revises: a7df296e5ce7
Create Date: 2026-08-09 00:34:26.486387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971c78d38345'
down_revision = 'a7df296e5ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correspondents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correspondents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correspondents_phone_number'), ['phone_number'], unique=True)

    op.create_table('whatsapp_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correspondent_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('text_buffer', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['correspondent_id'], ['correspondents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('source')

    op.drop_table('whatsapp_drafts')
    with op.batch_alter_table('correspondents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correspondents_phone_number'))

    op.drop_table('correspondents')
    # ### end Alembic commands ###
