"""mots cles importance

Revision ID: c994352a1754
Revises: 750dc499cf93
Create Date: 2026-08-11 20:46:27.456288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c994352a1754'
down_revision = '750dc499cf93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scoring_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('importance_keywords', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scoring_configs', schema=None) as batch_op:
        batch_op.drop_column('importance_keywords')

    # ### end Alembic commands ###
