"""statuts editoriaux etendus et publication programmee

Revision ID: eece957e60d3
Revises: 90893b39bfc8
Create Date: 2026-08-21 09:47:13.892800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eece957e60d3'
down_revision = '90893b39bfc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('scheduled_at')

    # ### end Alembic commands ###
