"""proposition pulaar : definition_ff et definition_fr facultative

Revision ID: f95738c58aa2
Revises: 45686c2c9466
Create Date: 2026-09-01 07:07:48.590139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95738c58aa2'
down_revision = '45686c2c9466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pulaar_proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('definition_ff', sa.Text(), nullable=True))
        batch_op.alter_column('definition_fr',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pulaar_proposals', schema=None) as batch_op:
        batch_op.alter_column('definition_fr',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('definition_ff')

    # ### end Alembic commands ###
